#!/usr/bin/env python
# Merge the .txt files in the src-dir to one dictionary.

import sys
import os

def write_dict(src_set, path):
    f = open(path, 'w')
    for word in src_set:
        f.write(word)

def read_dict(path, dst_set):
    f = open(path, 'r')
    while True:
        w = f.readline()
        if w == '': break
        dst_set.add(w)

def main(argv):
    if len(argv) != 3:
        print('Usage:\nmerge-dict src-dir dst-file', file=sys.stderr)
        exit(1)
    dic = set()
    for root, dirs, files in os.walk(argv[1]):
        for name in files:
            if name.endswith('.txt'):
                fullpath = os.path.join(root, name)
                read_dict(fullpath, dic)
    write_dict(dic, argv[2])

if __name__ == '__main__':
    main(sys.argv)
