# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Apr 11 15:06:07 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(790, 592)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.rbtn_eng = QtGui.QRadioButton(self.centralwidget)
        self.rbtn_eng.setChecked(True)
        self.rbtn_eng.setObjectName(_fromUtf8("rbtn_eng"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.rbtn_eng)
        self.horizontalLayout.addWidget(self.rbtn_eng)
        self.rbtn_chn = QtGui.QRadioButton(self.centralwidget)
        self.rbtn_chn.setObjectName(_fromUtf8("rbtn_chn"))
        self.buttonGroup.addButton(self.rbtn_chn)
        self.horizontalLayout.addWidget(self.rbtn_chn)
        self.cbStrict = QtGui.QCheckBox(self.centralwidget)
        self.cbStrict.setChecked(True)
        self.cbStrict.setObjectName(_fromUtf8("cbStrict"))
        self.horizontalLayout.addWidget(self.cbStrict)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tw_eng = QtGui.QTableWidget(self.splitter)
        self.tw_eng.setObjectName(_fromUtf8("tw_eng"))
        self.tw_eng.setColumnCount(0)
        self.tw_eng.setRowCount(0)
        self.tw_eng.horizontalHeader().setStretchLastSection(True)
        self.tw_eng.verticalHeader().setStretchLastSection(False)
        self.tw_chn = QtGui.QTableWidget(self.splitter)
        self.tw_chn.setObjectName(_fromUtf8("tw_chn"))
        self.tw_chn.setColumnCount(0)
        self.tw_chn.setRowCount(0)
        self.tw_chn.horizontalHeader().setStretchLastSection(True)
        self.tw_chn.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.splitter)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_About = QtGui.QMenu(self.menubar)
        self.menu_About.setObjectName(_fromUtf8("menu_About"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setIconVisibleInMenu(True)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_exit_2 = QtGui.QAction(MainWindow)
        self.action_exit_2.setIconVisibleInMenu(True)
        self.action_exit_2.setObjectName(_fromUtf8("action_exit_2"))
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setIconVisibleInMenu(True)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_about_qt = QtGui.QAction(MainWindow)
        self.action_about_qt.setIconVisibleInMenu(True)
        self.action_about_qt.setObjectName(_fromUtf8("action_about_qt"))
        self.action_search = QtGui.QAction(MainWindow)
        self.action_search.setEnabled(False)
        self.action_search.setIconVisibleInMenu(True)
        self.action_search.setObjectName(_fromUtf8("action_search"))
        self.action_clear = QtGui.QAction(MainWindow)
        self.action_clear.setIconVisibleInMenu(True)
        self.action_clear.setObjectName(_fromUtf8("action_clear"))
        self.action_stop = QtGui.QAction(MainWindow)
        self.action_stop.setEnabled(False)
        self.action_stop.setIconVisibleInMenu(True)
        self.action_stop.setObjectName(_fromUtf8("action_stop"))
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_open)
        self.menu_File.addAction(self.action_search)
        self.menu_File.addAction(self.action_stop)
        self.menu_File.addAction(self.action_clear)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_exit_2)
        self.menu_About.addAction(self.action_about)
        self.menu_About.addAction(self.action_about_qt)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.toolBar.addAction(self.action_open)
        self.toolBar.addAction(self.action_search)
        self.toolBar.addAction(self.action_stop)
        self.toolBar.addAction(self.action_clear)
        self.toolBar.addAction(self.action_exit_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ReGui", None, QtGui.QApplication.UnicodeUTF8))
        self.rbtn_eng.setText(QtGui.QApplication.translate("MainWindow", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.rbtn_chn.setText(QtGui.QApplication.translate("MainWindow", "Chinese", None, QtGui.QApplication.UnicodeUTF8))
        self.cbStrict.setText(QtGui.QApplication.translate("MainWindow", "Strict", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_About.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>About</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit_2.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit_2.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about_qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about_qt.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search.setText(QtGui.QApplication.translate("MainWindow", "&Search", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_clear.setText(QtGui.QApplication.translate("MainWindow", "&Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.action_clear.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.action_stop.setText(QtGui.QApplication.translate("MainWindow", "&Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.action_stop.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))

